{
 "title": "Mini Air Quality Station",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Temperature & Humidity & Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"TEMPERATURE\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    },
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"HUMIDITY\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    },
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PRESSURE\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    }
   ]
  },
  {
   "title": "Particles",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PM1\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    },
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PM2_5\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    },
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PM10\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"TEMPERATURE\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"HUMIDITY\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PRESSURE\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    }
   ]
  },
  {
   "title": "Particle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PM1\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    },
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PM2_5\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    },
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"PM10\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median)"
    }
   ]
  }
 ]
}